begin;
select plan(10);

create temporary table test_fixtures (key text primary key, value uuid);

insert into public.studios (id, name) values ('99999999-0002-0000-0000-000000000001', 'Studio K');
insert into test_fixtures values ('studio_k', '99999999-0002-0000-0000-000000000001');
insert into test_fixtures (key, value)
  select 'owner_k', tests.create_test_profile((select value from test_fixtures where key = 'studio_k'), 'owner', 'Owner K');
insert into test_fixtures (key, value)
  select 'instructor_k', tests.create_test_profile((select value from test_fixtures where key = 'studio_k'), 'instructor', 'Instructor K');

-- Two brand-new auth.users rows with no profile yet, created up front while
-- the session is still `postgres` -- same reasoning/ordering constraint as
-- invites.test.sql's new_user/second_user fixtures (auth.users isn't
-- grant-accessible to authenticated/anon, so this has to happen before any
-- authenticate_as/clear_authentication role switch).
insert into test_fixtures (key, value) values ('registered_user', gen_random_uuid());
insert into auth.users (id, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, aud, role)
values ((select value from test_fixtures where key = 'registered_user'), 'registered@test.local', '', now(), now(), now(), '{}', '{}', 'authenticated', 'authenticated');

insert into test_fixtures (key, value) values ('plain_invite_user', gen_random_uuid());
insert into auth.users (id, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, aud, role)
values ((select value from test_fixtures where key = 'plain_invite_user'), 'plaininvite@test.local', '', now(), now(), now(), '{}', '{}', 'authenticated', 'authenticated');

-- insert too, not just select: assertion 6 below inserts into test_fixtures
-- (stashing the registration id) while already authenticate_as(owner_k), a
-- role switch that has already happened by then.
grant select, insert on test_fixtures to authenticated, anon;

-- 1) the owner's 3-step wizard creates an invite + registration atomically
select tests.authenticate_as((select value from test_fixtures where key = 'owner_k'));
select public.register_member(
  'REGCODE01', '김등록', '010-1111-2222', 'reg@test.local',
  'w3', 3, current_date, array['하타 요가'], 165000,
  '{"terms":true,"privacy":true,"refund":true,"safety":true,"marketing":false,"photo":false}'::jsonb,
  '김등록'
);
select is(
  (select role::text from public.invites where code = 'REGCODE01'),
  'member',
  'register_member creates a member invite with the given code'
);
select is(
  (select full_name from public.member_registrations where invite_id = (select id from public.invites where code = 'REGCODE01')),
  '김등록',
  'register_member records the registration with the invite linked'
);

-- 2) a non-owner cannot register a member
select tests.authenticate_as((select value from test_fixtures where key = 'instructor_k'));
select throws_ok(
  $$select public.register_member('REGCODE02', '거절될등록', '010-0000-0000', 'x@test.local', 'w2', 1, current_date, array[]::text[], 130000, '{}'::jsonb, '거절될등록')$$,
  'not_permitted',
  'a non-owner cannot register a member'
);

-- 3) missing required fields are rejected
select tests.authenticate_as((select value from test_fixtures where key = 'owner_k'));
select throws_ok(
  $$select public.register_member('REGCODE03', '', '010-0000-0000', 'x@test.local', 'w2', 1, current_date, array[]::text[], 130000, '{}'::jsonb, '서명')$$,
  'missing_required_field',
  'a blank full_name is rejected'
);

-- 4) a missing signature is rejected
select throws_ok(
  $$select public.register_member('REGCODE04', '이름', '010-0000-0000', 'x@test.local', 'w2', 1, current_date, array[]::text[], 130000, '{}'::jsonb, '   ')$$,
  'missing_signature',
  'a blank signature is rejected'
);

-- 5) accepting the invite generated by register_member goes straight to
-- 'signed', not 'pending' -- the whole point of doing the paperwork up front
select tests.authenticate_as((select value from test_fixtures where key = 'registered_user'));
select public.accept_invite('REGCODE01', '김등록');
select is(
  (select contract_status from public.profiles where id = (select value from test_fixtures where key = 'registered_user')),
  'signed',
  'accepting a pre-registered invite sets contract_status to signed, skipping pending'
);

-- 6) and the registration row is linked back to the new profile -- read as
-- the owner here to keep this assertion about the backfill itself; the new
-- member's own read access to this same row is assertion 9 below
-- (20260808000001_member_registrations_self_read.sql). Also stashes the
-- registration's own id into test_fixtures while still authenticated as the
-- owner: assertion 9 runs as registered_user (role 'member'), who has no
-- RLS access to the `invites` table at all, so re-deriving it there via
-- `where invite_id = (select id from invites where code = ...)` would
-- silently resolve that subquery to NULL and match zero rows -- not a
-- member_registrations RLS problem, an invites RLS problem one join away
-- from the thing actually under test (confirmed by hand before adding this
-- fixture capture).
select tests.authenticate_as((select value from test_fixtures where key = 'owner_k'));
insert into test_fixtures (key, value)
  select 'reg_reg01', id from public.member_registrations where invite_id = (select id from public.invites where code = 'REGCODE01');
select is(
  (select profile_id from public.member_registrations where id = (select value from test_fixtures where key = 'reg_reg01')),
  (select value from test_fixtures where key = 'registered_user'),
  'the registration is backfilled with the new profile''s id once accepted'
);

-- 7) regression: a plain invite (no registration behind it, the existing
-- 회원 초대 링크 발급 shortcut) still lands on 'pending' as before
select tests.bypass_rls();
insert into public.invites (id, studio_id, role, code, expires_at, created_by) values
  ('99999999-0002-0000-0000-000000000002', (select value from test_fixtures where key = 'studio_k'), 'member', 'PLAINCODE', now() + interval '7 days', (select value from test_fixtures where key = 'owner_k'));
select tests.authenticate_as((select value from test_fixtures where key = 'plain_invite_user'));
select public.accept_invite('PLAINCODE', '평범가입');
select is(
  (select contract_status from public.profiles where id = (select value from test_fixtures where key = 'plain_invite_user')),
  'pending',
  'an ordinary invite with no registration behind it still lands on pending, unchanged'
);

-- 8) RLS: a non-owner with no registration of their own sees zero rows
select tests.authenticate_as((select value from test_fixtures where key = 'instructor_k'));
select is(
  (select count(*)::int from public.member_registrations),
  0,
  'a non-owner with no registration of their own sees zero member_registrations rows'
);

-- 9) a member CAN read their own registration row (QA sweep 2026-08-08, item
-- 17 -- the missing "내 회원권" screen's RLS half; lib/actions/roster.ts's
-- getMemberDetail(profileId) does the actual query shape this backs).
select tests.authenticate_as((select value from test_fixtures where key = 'registered_user'));
select is(
  (select full_name from public.member_registrations where id = (select value from test_fixtures where key = 'reg_reg01')),
  '김등록',
  'a member can read their own member_registrations row'
);

select tests.clear_authentication();
select finish();
rollback;
